version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - CORS_ALLOW_ORIGINS=*
    restart: always
    networks:
      - cicd_net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    restart: always
    networks:
      - cicd_net

networks:
  cicd_net:
    name: cicd_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1
